version: '3'
services:
    course:
        container_name: course_service
        restart: always
        build: .
        ports: 
            - "5001:5001"
        env_file: 
            - .env
        links: 
            - pg
        volumes: 
            - .:/usr/src/app   
    pg:
        container_name: pg
        image: "postgres" # use latest official postgres version
        ports:
            - 5432:5432
        env_file: 
            - .env
        #volumes:
        #  - ./postgres-data:/var/lib/postgresql/data        
        #logging: 
        #    driver: none